name: Build & Deploy to Hostinger

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --workspace=client

      - name: Deploy to Hostinger deploy repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.HOSTINGER_DEPLOY_TOKEN }}
          external_repository: apexsoftware-solutions/CapturedMagicDeploy
          publish_branch: main
          publish_dir: ./client/dist
