name: Build & Deploy to Hostinger
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --workspace=client

      - name: Push to deploy branch
        uses: s0/git-publish-subdir-action@v2
        env:
          REPO: https://github.com/apexsoftware-solutions/CapturedMagicPhotography.git
          BRANCH: main # <- or 'build' if you set that in Hostinger
          FOLDER: client/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
