name: Build & Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout (disable default creds; we'll use your DEPLOY_TOKEN)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2) Setup Node (simple)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3) Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      # 4) Build frontend
      - name: Build frontend
        working-directory: client
        run: npm run build

      # 5) Inspect build output (helps verify publish_dir)
      - name: Inspect build output
        run: |
          echo "Root contents:" && ls -la
          echo "Client contents:" && ls -la client || true
          echo "client/dist:" && ls -la client/dist || true
          echo "client/build:" && ls -la client/build || true

      # 6) Deploy to Hostinger repo using your DEPLOY_TOKEN
      - name: Deploy to Hostinger repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: apexsoftware-solutions/CapturedMagicDeploy
          publish_branch: main            # <-- change to target repo's default if not 'main'
          # adjust this depending on build output (vite -> dist, CRA -> build)
          publish_dir: client/dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
